[package]
name = "hermes-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
futures-core.workspace = true
hermes-protocol = { path = "../hermes-protocol" }
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true

