[package]
name = "hermes-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
dioxus = { workspace = true, features = ["asset", "document", "hooks", "html", "macro", "router", "signals"] }
hermes-core = { path = "../hermes-core" }
hermes-protocol = { path = "../hermes-protocol" }

[lints]
workspace = true
